- id: startup
  alias: Startup
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: google_assistant.request_sync
    data:
      agent_user_id: e39e4023324640a1a5867893e80c3e8c

- id: bathroom_switch_1_hold
  alias: Bathroom Switch "ON" Hold
  trigger:
  - platform: state
    entity_id: sensor.bathroom_switch
    to: '1_hold'
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.bathroom_fan

- id: bathroom_switch_4_hold
  alias: Bathroom Switch "OFF" Hold
  trigger:
  - platform: state
    entity_id: sensor.bathroom_switch
    to: '4_hold'
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.bathroom_fan

- id: control_cd_player
  alias: Control CD Player
  trigger:
  - platform: state
    entity_id: switch.cd_player
  - platform: state
    entity_id: media_player.living_room_receiver
  condition: []
  action:
  - data_template:
      entity_id: >
        {% if trigger.entity_id == 'media_player.living_room_receiver' %}
          switch.cd_player
        {% else %}
          media_player.living_room_receiver
        {% endif %}
    service_template: >
      {% if trigger.entity_id == 'media_player.living_room_receiver' %}
        {% if trigger.to_state.attributes['source'] == 'CD' %}
          switch.turn_on
        {% elif trigger.from_state.attributes['source'] == 'CD' %}
          switch.turn_off
        {% else %}
          script.noop
        {% endif %}
      {% else %}
        {% if trigger.to_state.state == 'on' %}
          media_player.turn_on
        {% else %}
          {% if is_state_attr('media_player.living_room_receiver','source', 'CD') %}
            media_player.turn_off
          {% else%}
            script.noop
          {% endif %}
        {% endif %}
      {% endif %}
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ trigger.entity_id == 'switch.cd_player' }}"
      - condition: template
        value_template: "{{ trigger.to_state.state == 'on' }}"
      - condition: template
        value_template: "{{ state_attr('media_player.living_room_receiver','source') != 'CD' }}"
  - service: media_player.select_source
    data:
      entity_id: media_player.living_room_receiver
      source: 'CD'

- id: notify_light_unavailable
  alias: Notify Light Unavailable
  trigger:
  - entity_id: !include entity_lists/lights/lights.yaml
    for:
      minutes: 5
    platform: state
    to: 'unavailable'
  condition: []
  action:
  - data_template:
      title: "An entity is unavailable"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} has been {{ trigger.to_state.state }} for more than {{ trigger.for }} (was {{ trigger.from_state.state }})
      target: email/yinyang1994@gmail.com
    service: notify.pushbullet

- id: notify_zwave_unavailable
  alias: Notify Z-Wave Unavailable
  trigger:
  - entity_id:  !include entity_lists/zwave.yaml
    platform: state
    to: 'dead'
  condition: []
  action:
  - data_template:
      title: "An entity is unavailable"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} has been marked as {{ trigger.to_state.state }} (was {{ trigger.from_state.state }})
      target: email/yinyang1994@gmail.com
    service: notify.pushbullet

- id: notify_front_door
  alias: Notify Front Door Opened
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_sensor
    to: 'on'
  condition: []
  action:
  - service: notify.pushbullet
    data_template:
      target: email/yinyang1994@gmail.com
      title: "The Front Door is Open"
      message: >-
        The Front Door was opened at {{ as_timestamp(states.binary_sensor.front_door_sensor.last_updated ) | timestamp_custom("%I:%M %p on %a %b %d (%Y-%m-%d %H:%M:%S)", true) -}}

- id: arrival
  alias: Arrival Home
  trigger: # Assume the door opening means some one is coming home, for now.
  - platform: state
    entity_id: binary_sensor.front_door_sensor
    to: 'on'
  condition: []
  action:
  - condition: or
    conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  - service: light.turn_on
    data_template:
      entity_id: 
      - light.living_room
      brightness: "{{ [128, state_attr('light.living_room', 'brightness') | int] | max }}"
      kelvin: "{{ state_attr('sensor.circadian_values', 'colortemp') }}"
  - service: light.turn_on
    data_template:
      entity_id: 
      - light.kitchen
      brightness: "{{ [128, state_attr('light.kitchen', 'brightness') | int] | max }}"
      kelvin: "{{ state_attr('sensor.circadian_values', 'colortemp') }}"

- id: control_bedroom_tv
  alias: Control Bedroom TV
  trigger: 
  - platform: state
    entity_id: media_player.bedroom_tv
  condition: []
  action:
  - service_template: >
      {%- if trigger.from_state.state == 'off' and trigger.to_state.state != 'unavailable' -%}
        switch.turn_on
      {%- elif trigger.to_state.state == 'off' and trigger.from_state.state != 'unavailable' -%}
        switch.turn_off
      {%- else -%}
        script.noop
      {%- endif -%}
    data:
      entity_id: switch.bedroom_tv

- id: control_living_room_tv_lights
  alias: Control Living Room TV Lights
  trigger: 
  - platform: state
    entity_id: media_player.living_room_receiver
  condition: []
  action:
  - service_template: >
      {%- if trigger.to_state.state == 'off' and trigger.from_state.state != 'unavailable' -%}
        light.turn_off
      {%- else -%}
        script.noop
      {%- endif -%}
    data:
      entity_id: light.living_room_tv
  - service_template: >
      {%- if trigger.from_state.state == 'off' and trigger.to_state.state != 'unavailable' -%}
        light.turn_on
      {%- else -%}
        script.noop
      {%- endif -%}
    data:
      entity_id: light.living_room_tv
      brightness: 80