- id: startup
  alias: Startup
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: google_assistant.request_sync
    data:
      agent_user_id: 0c1ba4ded74d492a9624e710ed536eac

- id: bathroom_switch_1_hold
  alias: Bathroom Switch "ON" Hold
  trigger:
  - platform: state
    entity_id: sensor.bathroom_switch
    to: '1_hold'
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.bathroom_fan

- id: bathroom_switch_4_hold
  alias: Bathroom Switch "OFF" Hold
  trigger:
  - platform: state
    entity_id: sensor.bathroom_switch
    to: '4_hold'
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.bathroom_fan

- id: control_cd_player
  alias: Control CD Player
  trigger:
  - platform: state
    entity_id: switch.cd_player
  - platform: state
    entity_id: media_player.living_room_receiver
  condition: []
  action:
  - data_template:
      entity_id: >
        {% if trigger.entity_id == 'media_player.living_room_receiver' %}
          switch.cd_player
        {% else %}
          media_player.living_room_receiver
        {% endif %}
    service_template: >
      {% if trigger.entity_id == 'media_player.living_room_receiver' %}
        {% if trigger.to_state.attributes['source'] == 'CD' %}
          switch.turn_on
        {% elif trigger.from_state.attributes['source'] == 'CD' %}
          switch.turn_off
        {% else %}
          script.noop
        {% endif %}
      {% else %}
        {% if trigger.to_state.state == 'on' %}
          media_player.turn_on
        {% else %}
          {% if is_state_attr('media_player.living_room_receiver','source', 'CD') %}
            media_player.turn_off
          {% else%}
            script.noop
          {% endif %}
        {% endif %}
      {% endif %}
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ trigger.entity_id == 'switch.cd_player' }}"
      - condition: template
        value_template: "{{ trigger.to_state.state == 'on' }}"
      - condition: template
        value_template: "{{ state_attr('media_player.living_room_receiver','source') != 'CD' }}"
  - service: media_player.select_source
    data:
      entity_id: media_player.living_room_receiver
      source: 'CD'

- id: notify_unavailable
  alias: Notify Unavailable
  trigger:
  - entity_id: !include entity_lists/lights/lights.yaml
    for:
      minutes: 5
    platform: state
    to: 'unavailable'
  condition: []
  action:
  - data_template:
      title: "An entity is unavailable"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} has been {{ trigger.to_state.state }} for more than {{ trigger.for }} (was {{ trigger.from_state.state }})
      target: email/yinyang1994@gmail.com
    service: notify.pushbullet
