### binary_sensor.yaml
- platform: huesensor

- platform: template
  sensors:
    front_door_sensor:
        friendly_name: "Front Door Sensor"
        device_class: door
        value_template: "{{ is_state('sensor.front_door_sensor_access_control', '22') }}"