homeassistant:
  name: Home
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  elevation: 4
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages

# includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

person: !include person.yaml
zone: !include zone.yaml

binary_sensor: !include binary_sensor.yaml
device_tracker: !include device_tracker.yaml
switch: !include switch.yaml
media_player: !include media_player.yaml

google_assistant: !include google_assistant.yaml

# UI Components
# introduction: # Show links to resources in log and frontend
frontend: # Enables the frontend
map: # Enables a map showing the location of tracked devices
logbook: # View all events in a logbook
history: # Enables support for tracking state changes over time
config: # Enables configuration UI
conversation: # Allows you to issue voice commands from the frontend in enabled browsers
system_health: # Displays information on the system and its components
hassio: # Add the hassio tab

lovelace: # Use lovelace UI
  mode: yaml

updater: # Checks for available updates
  include_used_components: true

http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.2
    - 10.0.0.3

discovery: # Discover some devices automatically
sun: # Track the sun

weather: # Weather prediction
  - platform: openweathermap
    api_key: !secret openweather_api

tts: # Text to speech
  - platform: google
    base_url: http://10.0.0.4:8123

zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  network_key: !secret zwave_network_key

custom_updater:
  show_installable: true
  component_urls:
  - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
  - https://raw.githubusercontent.com/claytonjn/hass-circadian_lighting/master/custom_updater.json

sensor:
  - platform: huesensor

notify:
  - platform: pushbullet
    name: pushbullet
    api_key: !secret pushbullet_api

circadian_lighting:
  min_colortemp: 2800
  max_colortemp: 10000
  sunrise_offset: '-00:30'
  sunset_offset: '00:30'
