homeassistant:
  name: Home
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  elevation: 4
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

# includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# UI Components
# introduction: # Show links to resources in log and frontend
frontend:
map:
logbook:
history:
config:
conversation:

updater:
  include_used_components: true

http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

discovery:
sun:

tts:
  - platform: google
    base_url: http://10.0.0.3:8123

sensor:
  - platform: yr

zwave:
  usb_path: /dev/zwaveusbstick
  network_key: !secret zwave_network_key
