  version: '2'
  services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/raspberrypi3-homeassistant
      volumes:
        - /etc/homeassistant:/config
        - /etc/localtime:/etc/localtime:ro
      devices:
        - /dev/ttyACM0:/dev/ttyACM0
      restart: always
      network_mode: host
