title: Home

resources:
  - url: /local/plugins/custom-lovelace/group-card/group-card.js
    type: js
  - url: /local/plugins/lovelace-card-tools/card-tools.js
    type: js
  - url: /local/plugins/lovelace-layout-card/layout-card.js
    type: js
  - url: /local/plugins/custom-lovelace/monster-card/monster-card.js
    type: js
  - url: /local/plugins/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /local/github/custom-cards/tracker-card.js?track=true
    type: module

views:
  - title: Home
    icon: 'mdi:home'
    path: home
    cards:
      - type: glance
        title: House Members
        show_header_toggle: false
        entities:
          - entity: person.alex
          - entity: person.mads
      - type: glance
        title: Lights
        columns: 4
        entities:
          - entity: group.lights
            name: All Lights
            tap_action:
              action: toggle
          - entity: light.living_room
            name: Living Room
            tap_action:
              action: toggle
          - entity: light.dining_room
            name: Dining Room
            tap_action:
              action: toggle
          - entity: light.kitchen
            name: Kitchen
            tap_action:
              action: toggle
          - entity: light.bathroom
            name: Bathroom
            tap_action:
              action: toggle
          - entity: light.bedroom
            name: Bedroom
            tap_action:
              action: toggle
          - entity: light.office
            name: Office
            tap_action:
              action: toggle
          - entity: light.hallway
            name: Hallway
            tap_action:
              action: toggle
      - type: glance
        title: Switch
        entities:
          - entity: switch.circadian_lighting_circadian_lighting
            tap_action:
              action: toggle
          - entity: switch.bathroom_fan
            tap_action:
              action: toggle
          - entity: switch.cd_player
            tap_action:
              action: toggle
          - entity: switch.bedroom_tv
            tap_action:
              action: toggle
      - type: entity-filter
        state_filter:
          - 'on'
          - playing
          - paused
          - idle
          - standby
        card:
          type: entities
          title: Now Playing
          show_header_toggle: false
        show_empty: false
        entities:
          - entity: media_player.living_room_receiver
          - entity: media_player.shield_tv
          - entity: media_player.kodi
          - entity: media_player.playstation_4
          - entity: media_player.living_room_tv
            icon: 'mdi:cast'
          - entity: media_player.living_room_audio
            icon: 'mdi:cast'
          - entity: switch.cd_player
          - entity: media_player.kitchen_display
          - entity: media_player.bathroom_mini
          - entity: media_player.bedroom_display
          - entity: media_player.bedroom_tv
          - entity: media_player.office_mini
          - entity: media_player.back_rooms
            name: Back Rooms Cast Group
          - entity: media_player.front_of_house
            name: Front of House Cast Group
          - entity: media_player.back_of_house
            name: Back of House Cast Group
          - entity: media_player.whole_house
            name: Whole House Cast Group
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: Current Alarm/Timers
          show_header_toggle: false
        filter:
          include:
          - entity_id: sensor.kitchen_display_timer
          - entity_id: sensor.bathroom_mini_timer
          - entity_id: sensor.bedroom_display_timer
          - entity_id: sensor.office_mini_timer
          - entity_id: sensor.kitchen_display_alarm
          - entity_id: sensor.bathroom_mini_alarm
          - entity_id: sensor.bedroom_display_alarm
          - entity_id: sensor.office_mini_alarm
          exclude:
          - state: "unavailable"
      - type: weather-forecast
        entity: weather.openweathermap

  - title: Lights
    icon: 'mdi:lightbulb'
    path: lights
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - type: custom:fold-entity-row
            head: light.living_room
            items:
            - entity: light.living_room_north_lamp
            - entity: light.living_room_south_lamp
          - type: custom:fold-entity-row
            head: light.living_room_tv
            items:
            - entity: light.living_room_tv_left
            - entity: light.living_room_tv_right
      #- type: entities
      #  show_header_toggle: false
      #  entities:
      #    - type: custom:fold-entity-row
      #      head: light.dining_room
      #      items:
      - type: entities
        show_header_toggle: false
        entities:
          - type: custom:fold-entity-row
            head: light.kitchen
            items:
          - entity: light.kitchen_light_n
          - entity: light.kitchen_light_s
      - type: entities
        show_header_toggle: false
        entities:
          - type: custom:fold-entity-row
            head: light.bathroom
            items:
          - entity: light.bathroom_light_a
          - entity: light.bathroom_light_b
          - entity: light.bathroom_light_c
          - entity: light.bathroom_light_d
      - type: entities
        show_header_toggle: false
        entities:
          - type: custom:fold-entity-row
            head: light.bedroom
            items:
          - entity: light.bedroom_lamp
            - entity: light.alex_s_lamp
          - entity: light.mads_lamp
      - type: entities
        show_header_toggle: false
        entities:
          - type: custom:fold-entity-row
            head: light.office
            items:
          - entity: light.office_lamp
            - entity: light.guest_bed_lamp
      - type: entities
        show_header_toggle: false
        entities:
          - entity: light.hallway_light

  - title: Media
    icon: 'mdi:play-pause'
    path: media
    cards:
      - type: entities
        entities:
          - entity: media_player.living_room_receiver
          - entity: media_player.shield_tv
          - entity: media_player.kodi
          - entity: media_player.playstation_4
          - entity: media_player.living_room_tv
          - entity: media_player.living_room_audio
          - entity: switch.cd_player
      - type: entities
        entities:
          - entity: media_player.kitchen_display
      - type: entities
        entities:
          - entity: media_player.bathroom_mini
      - type: entities
        entities:
          - entity: media_player.bedroom_display
          - entity: media_player.bedroom_tv
          - entity: media_player.bedroom
            name: Bedroom Cast Group
      - type: entities
        entities:
          - entity: media_player.office_mini
      - type: entities
        entities:
          - entity: media_player.back_rooms
            name: Back Rooms Cast Group
          - entity: media_player.front_of_house
            name: Front of House Cast Group
          - entity: media_player.back_of_house
            name: Back of House Cast Group
          - entity: media_player.whole_house
            name: Whole House Cast Group

  - title: People
    icon: 'mdi:account-multiple'
    path: people
    cards:
      - type: custom:group-card
        group: group.people
        card:
          type: entity-filter
          state_filter:
            - 'home'
          show_empty: false
          card:
            type: glance
            title: Who's Here?
            show_state: false
      - title: House Members
        type: map
        entities:
          - entity: person.alex
          - entity: person.mads
      # Leaving out for now, no guests set up yet
      #- type: 'custom:group-card'
      #  group: group.guests
      #  card:
      #    title: Guests
      #    type: entities
      #    show_header_toggle: false

  - title: Info
    icon: 'mdi:information'
    path: info
    panel: true
    cards:
    - type: custom:layout-card
      column_width: 500
      # max_columns: 4
      # max_width: 100%
      cards:
      - type: glance
        columns: 4
        entities:
          - entity: sun.sun
          - entity: binary_sensor.front_door_sensor
          name: Front Door
          - entity: sensor.htc10_battery
          - entity: sensor.clark_battery
      - type: entities
        title: Malden Center
        show_header_toggle: false
        entities:
        - entity: sensor.malden_center_inbound_departure
          name: Next Inbound Depature
        - entity: sensor.malden_center_outbound_arrival
          name: Next Outbound Arrival
      - type: entities
        title: Timers
        show_header_toggle: false
        entities:
        - entity: sensor.kitchen_display_timer
        - entity: sensor.bathroom_mini_timer
        - entity: sensor.bedroom_display_timer
        - entity: sensor.office_mini_timer
      - type: entities
        title: Alarms
        show_header_toggle: false
        entities:
        - entity: sensor.kitchen_display_alarm
        - entity: sensor.bathroom_mini_alarm
        - entity: sensor.bedroom_display_alarm
        - entity: sensor.office_mini_alarm
      - type: entities
        title: Hue Switches
        show_header_toggle: false
        entities:
          - entity: sensor.bathroom_switch
          - entity: sensor.bedroom_switch
          - entity: sensor.living_room_and_kitchen_switch
          - entity: sensor.office_switch

  - title: Network
    icon: 'mdi:network'
    path: net
    cards:
      - type: entities
        title: Z-Wave
        show_header_toggle: false
        entities:
          - entity: zwave.aeotec_zw090_z_stick_gen5_us
          - entity: zwave.bathroom_fan
          - entity: zwave.front_door_sensor
      - type: 'custom:group-card'
        group: group.all_devices
        card:
          type: entities
          title: Devices
          show_header_toggle: false
      - type: history-graph
        entities:
          - sensor.tplink_archer_c9_dd_wrt_packets_sec_sent
          - sensor.tplink_archer_c9_dd_wrt_packets_sent
          - sensor.tplink_archer_c9_dd_wrt_kbyte_sec_sent
          - sensor.tplink_archer_c9_dd_wrt_bytes_received
          - sensor.tplink_archer_c9_dd_wrt_packets_received
          - sensor.tplink_archer_c9_dd_wrt_packets_sec_received
          - sensor.tplink_archer_c9_dd_wrt_kbyte_sec_received
          - sensor.tplink_archer_c9_dd_wrt_bytes_sent
        
  - title: Settings
    icon: 'mdi:settings'
    path: settings
    cards:
      - type: 'custom:group-card'
        group: group.all_automations
        card:
          title: Automations
          type: entities
      - type: 'custom:group-card'
        group: group.all_scripts
        card:
          type: entities
          title: Scripts
          show_header_toggle: false
      - type: custom:tracker-card
